const express = require('express');
const path = require('path');
const multer = require('multer');
var upload = multer();


// Initialize server
const app = express();
const PORT = 3000;

// Declare routers 
const loginRouter = require('./routes/login');
const apiRouter = require('./routes/api');

// Global parser(s)
app.use(express.json());

// To parse form data from login page
app.use(express.urlencoded({ extended: true }));
app.use(upload.array());
app.use(express.static('public'));


// Serve static login page
app.use(express.static(path.resolve(__dirname, '../client')));

// Router(s)
app.use('/login', loginRouter);
app.use('/api', apiRouter);

// 404 bad endpoint catch
app.use((req, res, next)=>{
  // In the event a bad route send user to our 404.html page
  res.status(400).redirect('/404.html');
})

// Global error handler
app.use((err, req, res, next) => {
  const defaultError = {
    log: 'Default error generated by Unknown middleware',
    status: 500,
    err: {message: 'Unknown Error'}
  }

  const ourError = Object.assign({}, defaultError, err);
  console.log('Global Error Handler: ', ourError.log);
  res.status(ourError.status).json(ourError.message);
});


// Start server
app.listen(PORT, ()=>{
  console.log(`Server started and listening on port ${PORT}...`);
})